<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="SCSRuleList.aspx.cs" Inherits="UnicorntoSCSConverter.SCSRuleList"  %>
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:gridview ID="grdVwRuleList" runat="server" ShowFooter="True" AutoGenerateColumns="False" OnRowDeleting="grdVwRuleList_RowDeleting">

            <Columns>

                <asp:BoundField DataField="RuleID" HeaderText="Row Number" />

                <asp:TemplateField HeaderText="Scope">

                    <ItemTemplate>

                        <asp:DropDownList ID="ddlScope"   runat="server">
                            <asp:ListItem value="ItemAndDescendants">ItemAndDescendants</asp:ListItem>
                            <asp:ListItem value="ItemAndChildren">ItemAndChildren</asp:ListItem>
                            <asp:ListItem value="DescendantsOnly">DescendantsOnly</asp:ListItem>
                            <asp:ListItem value="SingleItem">SingleItem</asp:ListItem>
                            <asp:ListItem value="ignored">Ignored</asp:ListItem>
                        </asp:DropDownList>

                    </ItemTemplate>

                </asp:TemplateField>

                <asp:TemplateField HeaderText="Allowed Operation">

                    <ItemTemplate>

                        <asp:DropDownList ID="ddlAllowedOperation" runat="server">
                            <asp:ListItem value="CreateUpdateAndDelete">CreateUpdateAndDelete</asp:ListItem>
                            <asp:ListItem value="CreateAndUpdate">CreateAndUpdate</asp:ListItem>
                            <asp:ListItem value="CreateOnly">CreateOnly</asp:ListItem>
                        </asp:DropDownList>

                    </ItemTemplate>

                </asp:TemplateField>

                <asp:TemplateField HeaderText="Path">

                    <ItemTemplate>

                        <asp:TextBox ID="txtPath" runat="server"></asp:TextBox>

                    </ItemTemplate>

                    <FooterStyle HorizontalAlign="Right" />

                    <FooterTemplate>

                        <asp:Button ID="ButtonAdd" runat="server"  OnClick="btnSave_Click" Text="Add New Row" />

                    </FooterTemplate>

                </asp:TemplateField>

                <asp:ButtonField CommandName="Delete" HeaderText="Delete" ShowHeader="True" Text="Delete" />

            </Columns>
           <%-- <asp:GridView ID="grdVwRuleList" DataKeyNames="RuleID" AutoGenerateEditButton="True"

   AutoGenerateDeleteButton="True" runat="server" ShowFooter="True" AutoGenerateColumns="false"

   CellPadding="4" ForeColor="#333333" GridLines="None" onrowcommand="grdVwRuleList_RowCommand"

   onrowdatabound="grdVwRuleList_RowDataBound">

   <RowStyle BackColor="#EFF3FB" />

   <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />

   <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />

   <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />

   <AlternatingRowStyle BackColor="White" />

   <Columns>

     <asp:TemplateField Visible="false" HeaderText="RuleID" HeaderStyle-HorizontalAlign="Left">

       <ItemTemplate>

         <asp:Label ID="lblFirstName" runat="server" Text='<%#Eval("RuleID")%>' />

       </ItemTemplate>

     </asp:TemplateField>

    <asp:TemplateField HeaderText="Scope" HeaderStyle-HorizontalAlign="Left">

       <ItemTemplate>

          <asp:Label ID="lblScope" runat="server" Text='<%#Eval("Scope")%>' />

       </ItemTemplate>

       <EditItemTemplate>
           <asp:DropDownList ID="ddlScope"   runat="server" Text='<%# Bind("Scope") %>'>
               <asp:ListItem value="ItemAndDescendants">ItemAndDescendants</asp:ListItem>
               <asp:ListItem value="ItemAndChildren">ItemAndChildren</asp:ListItem>
               <asp:ListItem value="DescendantsOnly">DescendantsOnly</asp:ListItem>
               <asp:ListItem value="SingleItem">SingleItem</asp:ListItem>
               <asp:ListItem value="ignored">Ignored</asp:ListItem>
           </asp:DropDownList>
       </EditItemTemplate>

       <FooterTemplate>

           <asp:DropDownList ID="ddlScope"  runat="server">
               <asp:ListItem value="ItemAndDescendants">ItemAndDescendants</asp:ListItem>
               <asp:ListItem value="ItemAndChildren">ItemAndChildren</asp:ListItem>
               <asp:ListItem value="DescendantsOnly">DescendantsOnly</asp:ListItem>
               <asp:ListItem value="SingleItem">SingleItem</asp:ListItem>
               <asp:ListItem value="ignored">Ignored</asp:ListItem>
           </asp:DropDownList>

       </FooterTemplate>

     </asp:TemplateField>

     <asp:TemplateField HeaderText="Allowed Operation" HeaderStyle-HorizontalAlign="Left">

       <ItemTemplate>

         <asp:Label ID="lblAllowedOperation" runat="server" Text='<%#Eval("AllowedOperation")%>' />

       </ItemTemplate>

       <EditItemTemplate>
           <asp:DropDownList ID="ddlAllowedOperation" runat="server" Text='<%# Bind("AllowedOperation") %>'>
               <asp:ListItem value="CreateUpdateAndDelete">CreateUpdateAndDelete</asp:ListItem>
               <asp:ListItem value="CreateAndUpdate">CreateAndUpdate</asp:ListItem>
               <asp:ListItem value="CreateOnly">CreateOnly</asp:ListItem>
           </asp:DropDownList>
       </EditItemTemplate>

       <FooterTemplate>

           <asp:DropDownList ID="ddlAllowedOperation" runat="server">
               <asp:ListItem value="CreateUpdateAndDelete">CreateUpdateAndDelete</asp:ListItem>
               <asp:ListItem value="CreateAndUpdate">CreateAndUpdate</asp:ListItem>
               <asp:ListItem value="CreateOnly">CreateOnly</asp:ListItem>
           </asp:DropDownList>

       </FooterTemplate>

       <HeaderStyle HorizontalAlign="Left" />  

    </asp:TemplateField>

     <asp:TemplateField HeaderText="Path" HeaderStyle-HorizontalAlign="Left">

       <ItemTemplate>

         <asp:Label ID="lblPath" runat="server" Text='<%#Eval("Path")%>' />

       </ItemTemplate>

       <EditItemTemplate>

         <asp:TextBox ID="txtPath" runat="server" Text='<%#Eval("Path")%>' />

       </EditItemTemplate>

       <FooterTemplate>

         <asp:TextBox ID="txtPath" runat="server" />

       </FooterTemplate>

       <HeaderStyle HorizontalAlign="Left" />

    </asp:TemplateField>

    <asp:TemplateField>  

     <FooterTemplate>  

       <asp:Button ID="btnSave" runat="server" Text="Save" OnClick="btnSave_Click" />

      </FooterTemplate>

   </asp:TemplateField>

  </Columns>--%>

 </asp:GridView>  
        </div>
        <asp:ObjectDataSource ID="objRuleListDataSource"  TypeName="UnicorntoSCSConverter.SCSRuleList" InsertMethod="InsertRule" UpdateMethod="UpdateRule" DeleteMethod="DeleteRule" SelectMethod="GetAllRules" runat="server">
            <InsertParameters>
                <asp:Parameter Name="Path" />
                <asp:Parameter Name="AllowedOperation" />
                <asp:Parameter Name="Scope" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="Path" />
                <asp:Parameter Name="AllowedOperation" />
                <asp:Parameter Name="Scope" />
            </UpdateParameters>
            <DeleteParameters>
                <asp:Parameter Name="Path" />
                <asp:Parameter Name="AllowedOperation" />
                <asp:Parameter Name="Scope" />
            </DeleteParameters>
        </asp:ObjectDataSource>
    </form>
</body>
</html>
